/**
 * @agentic-trading/engine-sdk — Engine Author Types
 *
 * AUTO-GENERATED by packages/shared/generate-types.mjs
 * Do NOT edit manually.
 *
 * Regenerate:  pnpm --filter @agentic-trading/shared generate-types
 *
 * Install:     npm install -D @agentic-trading/engine-sdk
 * Raw URL:     https://raw.githubusercontent.com/miracleonyenma/agentic-trading/main/packages/shared/engine.d.ts
 *
 * Usage in tsconfig.json:
 *   {
 *     "compilerOptions": {
 *       "paths": { "@agentic-trading/shared": ["./node_modules/@agentic-trading/engine-sdk/index.d.ts"] }
 *     }
 *   }
 *
 * Engine module contract:
 *   export default function createEngine(ctx: EngineContext): IQuantEngine
 *   export const manifest: EngineManifest  // optional, recommended
 */

// ─── Market ─────────────────────────────────────────────────────────────────

export interface Candle {
  time:   number;   // Unix ms
  open:   number;
  high:   number;
  low:    number;
  close:  number;
  volume: number;
}

export interface OrderbookEntry {
  id:     string;
  price:  number;
  amount: number;
}

export interface Orderbook {
  market: string;
  bids:   OrderbookEntry[];
  asks:   OrderbookEntry[];
}

export interface Ticker {
  market:                string;
  lastPrice:             number;
  priceChangePercent24h: number;
  volume24h:             number;
  high24h:               number;
  low24h:                number;
}

// ─── Signal ─────────────────────────────────────────────────────────────────

/** Standard indicators returned by ctx.computeIndicators(). */
export interface Indicators {
  ema9:            number | null;
  ema21:           number | null;
  ema50:           number | null;
  rsi14:           number | null;
  macdLine:        number | null;
  macdSignal:      number | null;
  macdHistogram:   number | null;
  bbUpper:         number | null;
  bbMiddle:        number | null;
  bbLower:         number | null;
  volumeSma20:     number | null;
  currentVolume:   number | null;
  bidAskSpread:    number | null;
  /** (bidVol − askVol) / (bidVol + askVol), range −1 to 1. */
  bidAskImbalance: number | null;
  /** Engine-specific extra indicators — any additional numeric key is valid. */
  [key: string]: number | null | undefined;
}

export interface MarketSnapshot {
  market:         string;
  price:          number;
  bestBid?:       number | null;
  bestAsk?:       number | null;
  timestamp:      number;
  candleInterval: string;
  category?:      "spot" | "linear";
  exchangeId?:    string;
  marketAlias?:   string;
}

export type SignalAction =
  | "buy" | "sell" | "hold"
  | "open_long" | "close_long" | "open_short" | "close_short";

export interface Signal {
  id:             string;
  market:         string;
  timestamp:      number;
  action:         SignalAction;
  strength:       number;
  indicators:     Record<string, number | null>;
  marketSnapshot: MarketSnapshot;
  summary:        string;
  flags?: { bypassLlm?: boolean };
}

// ─── Agent ─────────────────────────────────────────────────────────────────

export type AgentInputKey =
  | "signal" | "openPositions" | "recentMemory" | "previousAgentOutput"
  | "balance" | "openOrders" | "riskLimits" | "instanceConfig" | "engineContext" | "exchangeData";

export interface AgentInput {
  signal: Signal;
  recentMemory: Record<string, unknown>[];
  /** Key matches the JSON sent to agents: previousAgentOutput */
  previousAgentOutput: Record<string, unknown> | null;
}

export interface AgentOutput {
  agentName: string;
  role: string;
  reasoning: string;
  recommendation: SignalAction;
  confidence: number;
  data: Record<string, unknown>;
  inputTokens?: number;
  outputTokens?: number;
  estimatedCostUsd?: number;
}

export interface RiskManagerData {
  approved: boolean;
  reason: string;
  /** Position size as % of available balance (0.5–100, capped at maxOrderSizePercent). */
  orderSizePercent?: number;
  /** Absolute position size in quote currency — overrides orderSizePercent when set. */
  orderSizeUsd?: number;
  /**
   * Absolute stop-loss price.
   * Honoured when on the correct side within agentSlMaxDeviationPct (default 30%) from entry.
   */
  stopLossPrice?: number;
  /** Absolute take-profit price. Honoured within agentTpMaxDeviationPct (default 50%). */
  takeProfitPrice?: number;
  /** Entry limit price. Overrides bestAsk/bestBid when within agentLimitPriceTightPct (default 2%) of market. */
  limitPrice?: number;
  /** Exchange-level trailing stop as fraction of entry price (e.g. 0.015 = 1.5%). */
  trailingStopPct?: number;
  /** Explicit execution intent. Preferred for futures and contract exchanges. */
  intent?: Exclude<SignalAction, "hold">;
  /** Override the engine signal direction. Takes precedence over finalDecision. */
  overrideAction?: SignalAction;
  /** Arbitrary tag stored on the trade record (max 64 chars). */
  tradeLabel?: string;
  /** Exact open position ID to close. */
  closePositionId?: string;
  /** Exact open position ID whose SL/TP protection should be updated. */
  updatePositionId?: string;
  /** Requested Bybit perpetual leverage. */
  setLeverage?: number;
}

export type StopReason =
  | "completed" | "veto" | "agent_error" | "agent_skipped_optional"
  | "circuit_breaker" | "insufficient_credits" | "early_hold" | "regime_veto";

export interface AgentTrace {
  id: string;
  signalId: string;
  tradeId: string | null;
  timestamp: number;
  agents: AgentOutput[];
  finalDecision: SignalAction;
  engineId?: string;
  totalInferenceCostUsd?: number;
  stopReason?: StopReason;
  voidedBy?: string | null;
  inputKeysJson?: string;
  pipelineInputJson?: string;
  executorSkipReason?: string | null;
}

// ─── Engine ─────────────────────────────────────────────────────────────────

export interface IndicatorConfig {
  ema: number[];
  rsi: { period: number };
  macd: { fast: number; slow: number; signal: number };
  bollingerBands: { period: number; stdDev: number };
  volumeSma: { period: number };
}

export interface TradeEvent {
  id: string;
  market: string;
  price: number;
  amount: number;
  timestamp: number;
}

export interface OrderbookUpdate {
  type: "add" | "update" | "remove";
  id: string;
  side: "buy" | "sell";
  price: number;
  amount: number;
  remaining: number;
  filled: number;
  timestamp: number;
}

export interface OpenPosition {
  id: string;
  /** Market symbol, e.g. "BTCUSDT". */
  market: string;
  price: number;
  amount: number;
  openedAt?: number;
  unrealizedPnl?: number | null;
  /** "long" for spot buys and futures longs; "short" for futures short positions. */
  positionSide?: "long" | "short";
  /** Average fill price (may differ from the limit price). */
  averageFillPrice?: number | null;
}

export type ExecutionIntent = "open_long" | "close_long" | "open_short" | "close_short";

export interface ExchangePositionSnapshot {
  market: string;
  side: "long" | "short";
  size: number;
  entryPrice: number;
  liquidationPrice: number | null;
  unrealizedPnl: number;
  leverage: number;
  timestamp: number;
  markPrice: number;
  positionValue: number;
  marginMode: "isolated" | "cross";
  positionIdx: 0 | 1 | 2;
  stopLoss: number | null;
  takeProfit: number | null;
}

export interface ExchangeOrderSnapshot {
  id: string;
  market: string;
  side: "buy" | "sell";
  type: "limit" | "market";
  price: number;
  amount: number;
  filled: number;
  remaining: number;
  status: "open" | "partial" | "filled" | "cancelled";
  stopLoss?: number;
  takeProfit?: number;
  timestamp: number;
}

export interface ExchangeExecutionData {
  exchangeId: string;
  market: string;
  productType: "spot" | "perpetual" | "contract";
  timestamp: number;
  capabilities: {
    supportedIntents: ExecutionIntent[];
    positions: boolean;
    leverage: boolean;
    funding: boolean;
    liquidationPrice: boolean;
    openInterest: boolean;
    volume: boolean;
    targetedClose: boolean;
    mutableProtection: boolean;
  };
  constraints: {
    tickSize: number | null;
    quantityStep: number | null;
    minQuantity: number | null;
    minNotional: number | null;
    maxLeverage: number | null;
  };
  fees: {
    /** Decimal fraction, e.g. 0.00055 = 0.055%. */
    makerRate: number | null;
    /** Decimal fraction, e.g. 0.00055 = 0.055%. */
    takerRate: number | null;
    /** Rate agents should use for conservative fee-aware decisions. */
    effectiveRate: number | null;
    source: "account" | "paper_config" | "unavailable";
    unit: "fraction";
  };
  marketData: {
    lastPrice: number | null;
    markPrice: number | null;
    indexPrice: number | null;
    bestBid: number | null;
    bestAsk: number | null;
    bidDepth: number | null;
    askDepth: number | null;
    volume24h: number | null;
    turnover24h: number | null;
    openInterest: number | null;
    openInterestValue: number | null;
    fundingRate: number | null;
    nextFundingTime: number | null;
  };
  positions: ExchangePositionSnapshot[];
  openOrders: ExchangeOrderSnapshot[];
  contract: {
    type: string;
    stake: number;
    currency: string;
    durationMinutes: number | null;
    multiplier: number | null;
    barrier: string | null;
    growthRate: number | null;
    payoutPerPoint: number | null;
  } | null;
  unsupportedFields: string[];
}

export interface ExchangeWsContext {
  connect(): void;
  subscribe(market: string): void;
  unsubscribe(market: string): void;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  on(event: string, listener: (...args: any[]) => void): void;
}

export interface EngineConfig {
  bot: {
    market: string;
    candleInterval: string;
    signalIntervalSeconds: number;
    signalPriceChangeThreshold: number;
  };
  risk: {
    positionProfitExitPct?: number;
    [key: string]: unknown;
  };
  indicators: Record<string, unknown>;
}

export interface EngineLogger {
  debug(bindings: Record<string, unknown>, msg?: string): void;
  info(bindings: Record<string, unknown>, msg?: string): void;
  warn(bindings: Record<string, unknown>, msg?: string): void;
  error(bindings: Record<string, unknown>, msg?: string): void;
  child(bindings: Record<string, unknown>): EngineLogger;
}

export interface EngineContext {
  config: EngineConfig;
  logger: EngineLogger;
  /**
   * Active exchange identity — set by the platform at startup.
   * Use ctx.exchange.category to adapt behaviour for spot vs futures.
   */
  exchange: {
    /** Exchange identifier: "bybit" | "100x" | "binance" | "deriv" */
    id:   string;
    /** Human-readable name, e.g. "Bybit" */
    name: string;
    /**
     * Trading category — present when the instance is configured for a specific mode.
     * "spot" = regular spot trading.
     * "linear" = USDT perpetual futures.
     * Absent for exchanges that don't distinguish (treat as "spot").
     *
     * Use this to emit explicit futures intents:
     *   isLinear ? "open_long" : "buy"
     *   isLinear ? "close_long" : "sell"
     */
    category?: "spot" | "linear";
    /**
     * Configured leverage for this instance (futures only).
     * 1 = no leverage (spot-equivalent). Absent for spot instances.
     * Use to scale ATR-based stop distances when designing stops.
     */
    leverage?: number;
  };
  /**
   * Per-instance resolved params. Prefer over process.env for multi-instance safety.
   * Cascade: InstanceConfig.params → instance secrets → global secrets → process.env
   */
  params: Record<string, string>;
  /** Fetch historical OHLCV candles from the exchange REST API. */
  getCandles(market: string, interval: string, limit: number): Promise<Candle[]>;
  /**
   * Returns all currently open positions for this instance.
   * Includes both longs (spot buys + futures longs) and shorts (futures shorts).
   * Check positionSide to distinguish direction.
   *
   * @example
   *   const longs  = ctx.getOpenPositions().filter(p => p.positionSide !== "short");
   *   const shorts = ctx.getOpenPositions().filter(p => p.positionSide === "short");
   */
  getOpenPositions(): OpenPosition[];
  /** Current capability-driven exchange market and execution context. */
  getExchangeData(): Promise<ExchangeExecutionData | null>;
  /** Shared exchange WebSocket — subscribe to live orderbook and trade events. */
  exchangeWs: ExchangeWsContext;
  /**
   * Compute technical indicators from candles + orderbook.
   * Returns ema9, ema21, ema50, rsi14, macdLine/Signal/Histogram,
   * bbUpper/Middle/Lower, volumeSma20, currentVolume, bidAskSpread, bidAskImbalance.
   */
  computeIndicators(candles: Candle[], orderbook: Orderbook | null, config: IndicatorConfig): Indicators;
  /**
   * Build a fully-formed Signal from candles + indicators.
   * The platform derives action/strength automatically from a multi-factor score.
   *
   * For futures engines, pass explicitAction to emit open_long/close_short etc. directly
   * instead of relying on the platform's generic buy/sell inference.
   *
   * @example — spot engine (platform infers direction)
   *   const signal = ctx.buildSignal(market, interval, candles, indicators, orderbook);
   *
   * @example — futures engine (explicit intent)
   *   const isLinear = ctx.exchange.category === "linear";
   *   const action = isLinear ? (bullish ? "open_long" : "open_short") : (bullish ? "buy" : "sell");
   *   const signal = ctx.buildSignal(market, interval, candles, indicators, orderbook, action);
   */
  buildSignal(
    market: string,
    candleInterval: string,
    candles: Candle[],
    indicators: Indicators,
    orderbook?: Orderbook | null,
    explicitAction?: SignalAction,
  ): Signal;
}

export interface ParamDefinition {
  /** Human-readable label shown in deployment UI. */
  label: string;
  /** Help text — may include a URL to obtain the value. */
  description?: string;
  /**
   * Value type.
   * "secret" → masked input, isSecret: true in Superrails, "[secret]" in receipt.
   * "select" → dropdown; requires options[].
   */
  type: "string" | "secret" | "number" | "boolean" | "select";
  /** Default: true. Optional params may be skipped. */
  required?: boolean;
  /** Pre-filled default value. NOT allowed on type: "secret". */
  default?: string | number | boolean;
  /** Allowed values — only for type: "select". */
  options?: string[];
  /** Input placeholder hint (e.g. "sk-..."). */
  placeholder?: string;
}

export interface EngineManifest {
  name: string;
  version: string;
  description?: string;
  /**
   * Map of indicator key → description.
   * Keys must match exactly what the engine puts in Signal.indicators.
   * Injected into every agent system prompt as a preamble.
   */
  indicators: Record<string, { type: string; description: string }>;
  /**
   * Map of env var name → param definition.
   * Collected from the user at deployment time; injected as Superrails env vars.
   * Engine reads values from process.env at runtime.
   *
   * @example
   * {
   *   "COINMARKETCAP_API_KEY": {
   *     "label": "CoinMarketCap API Key",
   *     "type": "secret",
   *     "required": true,
   *     "description": "Get one at coinmarketcap.com/api"
   *   }
   * }
   */
  params?: Record<string, ParamDefinition>;
  /** Optional URL to a AGENTS ZIP file pre-written for this engine's indicator set. */
  suggestedAgents?: string;
}

export interface IQuantEngine {
  start(): Promise<void>;
  stop(): void;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  on(event: string, listener: (...args: any[]) => void): this;
}

export type CreateEngine = (ctx: EngineContext) => IQuantEngine;
